# Generated by Django 5.2.6 on 2025-09-29 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='lorry_type',
            field=models.CharField(choices=[('mini', 'Mini Truck (₹1000)'), ('medium', 'Medium Truck (₹2000)'), ('large', 'Large Truck (₹3000)')], default='mini', max_length=20, null=True),
        ),
    ]
